# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/update_workout.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 322)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 2, 1, 1)
        self.radioButton_reps = QtWidgets.QRadioButton(Dialog)
        self.radioButton_reps.setObjectName("radioButton_reps")
        self.gridLayout.addWidget(self.radioButton_reps, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.radioButton_amrap = QtWidgets.QRadioButton(Dialog)
        self.radioButton_amrap.setObjectName("radioButton_amrap")
        self.gridLayout.addWidget(self.radioButton_amrap, 1, 2, 1, 1)
        self.lineEdit_reps = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_reps.setObjectName("lineEdit_reps")
        self.gridLayout.addWidget(self.lineEdit_reps, 4, 1, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout.addWidget(self.lineEdit_time, 6, 1, 1, 1)
        self.pushButton_remove = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove.sizePolicy().hasHeightForWidth())
        self.pushButton_remove.setSizePolicy(sizePolicy)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.gridLayout.addWidget(self.pushButton_remove, 8, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_rounds = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_rounds.setObjectName("lineEdit_rounds")
        self.gridLayout.addWidget(self.lineEdit_rounds, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lineEdit_value = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_value.setObjectName("lineEdit_value")
        self.gridLayout.addWidget(self.lineEdit_value, 4, 0, 1, 1)
        self.lineEdit_time_amrap = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_time_amrap.setObjectName("lineEdit_time_amrap")
        self.gridLayout.addWidget(self.lineEdit_time_amrap, 6, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.lineEdit_reps_amrap = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_reps_amrap.setObjectName("lineEdit_reps_amrap")
        self.gridLayout.addWidget(self.lineEdit_reps_amrap, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.radioButton_reps_in_time = QtWidgets.QRadioButton(Dialog)
        self.radioButton_reps_in_time.setObjectName("radioButton_reps_in_time")
        self.gridLayout.addWidget(self.radioButton_reps_in_time, 1, 1, 1, 1)
        self.radioButton_time = QtWidgets.QRadioButton(Dialog)
        self.radioButton_time.setChecked(True)
        self.radioButton_time.setObjectName("radioButton_time")
        self.gridLayout.addWidget(self.radioButton_time, 1, 0, 1, 1)
        self.pushButton_update = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update.sizePolicy().hasHeightForWidth())
        self.pushButton_update.setSizePolicy(sizePolicy)
        self.pushButton_update.setObjectName("pushButton_update")
        self.gridLayout.addWidget(self.pushButton_update, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Execise Name:"))
        self.label_6.setText(_translate("Dialog", "Total set time"))
        self.radioButton_reps.setText(_translate("Dialog", "Reps"))
        self.label_5.setText(_translate("Dialog", "Reps(AMRAP)"))
        self.radioButton_amrap.setText(_translate("Dialog", "AMRAP"))
        self.lineEdit_reps.setText(_translate("Dialog", "15"))
        self.lineEdit_time.setText(_translate("Dialog", "60"))
        self.pushButton_remove.setText(_translate("Dialog", "Remove"))
        self.lineEdit_rounds.setText(_translate("Dialog", "3"))
        self.label_3.setText(_translate("Dialog", "Reps(EMOM)"))
        self.label_2.setText(_translate("Dialog", "Rounds"))
        self.label.setText(_translate("Dialog", "Value"))
        self.lineEdit_value.setText(_translate("Dialog", "15"))
        self.lineEdit_time_amrap.setText(_translate("Dialog", "0"))
        self.lineEdit_reps_amrap.setText(_translate("Dialog", "0"))
        self.label_4.setText(_translate("Dialog", "Time(EMOM)"))
        self.radioButton_reps_in_time.setText(_translate("Dialog", "EMOM"))
        self.radioButton_time.setText(_translate("Dialog", "Time (is sec)"))
        self.pushButton_update.setText(_translate("Dialog", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
